export const flights = [
  {
    username: "neil",
    fromCity: "Mumbai",
    toCity: "Delhi",
    seat: "Window",
    airline: "Indigo",
    duration: 120,
    price: 4000,
    date: "22-10-20",
  },
  {
    username: "dev",
    fromCity: "Kolkata",
    toCity: "Bangalore",
    seat: "Aisle",
    airline: "Jet",
    duration: 180,
    price: 5000,
    date: "23-10-2020",
  },
  {
    username: "aditya",
    fromCity: "Delhi",
    toCity: "Chennai",
    seat: "Middle",
    airline: "Spice",
    duration: 160,
    price: 8000,
    date: "22-10-2020",
  },
  {
    username: "Soham",
    fromCity: "Gurgaon",
    toCity: "Mumbai",
    seat: "Window",
    airline: "Indigo",
    duration: 140,
    price: 6000,
    date: "22-10-2020",
  },
];

